name: atmos_connection
version: 0.16.1+1
description: "Dart helper package to work with connection by Atom735"
repository: https://github.com/Atom735/atmos_connection
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  async: ^2.8.2
  atmos_binary_buffer: ^0.16.5
  atmos_logger: ^0.16.1
  meta: ^1.7.0
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  atmos_lints: ^0.16.1
  test: ^1.20.2
